event:
  type: MinIOEventTrigger
  config:
    bucket: silver
    port: 5001

pipeline:
  - id: reader
    operator: MinioReader
    depends_on: MinIOEventTrigger
    params:
      access_key: minioadmin
      secret_key: minioadmin
      endpoint_url: http://localhost:9000

  - id: map_year
    operator: ValueMapper
    depends_on: reader
    params:
      column: frame
      use_regex: True
      regex_pattern: ".*?(20\\d{2}).*"
      regex_replacement: "\\1"

  - id: filter
    operator: ColumnFilter
    depends_on: map_year
    params:
      exclude: ["accn"]

  - id: insert_to_pg
    operator: PostgresInsertOperator
    depends_on: filter
    params:
      db_url: postgresql://myuser:mypassword@localhost:5432/mydatabase
      table: financial_data
