services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_NOTIFY_WEBHOOK_ENABLE_bronze_ingestion: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_bronze_ingestion: "http://host.docker.internal:5000/minio-event"
      MINIO_NOTIFY_WEBHOOK_ENABLE_silver_ingestion: "on"
      MINIO_NOTIFY_WEBHOOK_ENDPOINT_silver_ingestion: "http://host.docker.internal:5001/minio-event"
    command: server /data --console-address ":9001"
    volumes:
      #    - minio:/data
      - ./data/minio/:/data

  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc mb myminio/bronze;
        mc mb myminio/silver;
        exit 0;
      "

  registerevents:
    image: minio/mc:latest
    depends_on:
      - createbuckets
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 minioadmin minioadmin;
        mc event add myminio/bronze arn:minio:sqs::bronze_ingestion:webhook --event put || true;
        mc event add myminio/silver arn:minio:sqs::silver_ingestion:webhook --event put || true;
        mc admin service restart myminio;
        exit 0;
      "

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      #    - postgre:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgre/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  subjectstore_api:
    build:
      context: ./api
    container_name: subjectstore_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      #      - subjectstore:/app/data
      - ./data/subjectstore:/app/data

volumes:
  minio:
  postgre:
  pgadmin:
  subjectstore:
